FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11-run as run

RUN apk add ctop --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing --allow-untrusted \
	&& apk add --no-cache ttyd \
	&& rm -rf /var/cache/apk

CMD ["ttyd", "ctop"]
